on:
  push:
    branches:
      - main

name: Docker Build & Push

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login & Build & Push Docker Image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | \
          docker login ghcr.io --username $GITHUB_ACTOR --password-stdin
          docker buildx build --no-cache --push \
          --platform ${{ steps.buildx.outputs.platforms }} \
          --tag ghcr.io/$GITHUB_ACTOR/http1-server-sh:latest \
          --tag ghcr.io/$GITHUB_ACTOR/http1-server-sh:$(echo $GITHUB_SHA | head -c7) \
          .
